baseurl = ""
languageCode = "en-us"
title = "$ jazzfool.github.io"
theme = "Hugo-Octopress"
paginate = 6

disqusShortname = ""

[params]
  siteName = "jazzfool.github.io"
  author = "jazzfool"

  customCSS = ["/styles.css"]

  tableOfContents = true
  compactIndex = true
  navigationNewWindow = true
  enableFootnotes = false
  
  # Comments settigns
  [params.comments]
    enabled = false
    provider = ""

[menu]
[[menu.main]]
  name = "Articles"
  url = "/"
[[menu.main]]
  name = "GitHub"
  url = "https://github.com/jazzfool"

[markup]
  [markup.highlight]
    style = "solarized-dark"
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1

[outputs]
  home = ["HTML", "RSS", "JSON"]